service: lyft-webhooks

provider:
  name: aws
  runtime: java8
  stage: dev
  region: us-west-2

package:
  artifact: build/libs/lyft-webhooks-dev.jar

functions:
  webhook:
    handler: com.merricklabs.lyft.Handler
    events:
      - http:
          path: webhook
          method: post

# Todo: Grant privileges for Lambda to PUT to DynamoDB table
resources:
  Resources:
    RidesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: ride
            AttributeType: S
        KeySchema:
          -
            AttributeName: ride
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: Rides